/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bubblebot.jni;

public class bubblebotJNI {

	static {
		try {

			System.loadLibrary("bubblebot");
		} catch (UnsatisfiedLinkError e) {
			//badness
			throw e;
		}
	}


  public final static native long new_Processor__SWIG_0();
  public final static native String Processor_processViaJSON(long jarg1, Processor jarg1_, String jarg2);
  public final static native void delete_Processor(long jarg1);
}
