/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bubblebot.jni;

/** This class provides an interface to the image processing pipeline and handles most of the JSON parsing.
*/
public class Processor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Processor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Processor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bubblebotJNI.delete_Processor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Processor() {
    this(bubblebotJNI.new_Processor__SWIG_0(), true);
  }

  public String processViaJSON(String jsonString) {
    return bubblebotJNI.Processor_processViaJSON(swigCPtr, this, jsonString);
  }
}
